-- CreateEnum
CREATE TYPE "ProjectStage" AS ENUM ('IDEA', 'PROPOSAL', 'PLANNING', 'DESIGN', 'SIMULATION', 'IMPLEMENTATION', 'TESTING', 'DOCUMENTATION', 'PRESENTATION', 'COMPLETED');

-- AlterTable
ALTER TABLE "Workspace" ADD COLUMN     "stage" "ProjectStage" NOT NULL DEFAULT 'IDEA',
ADD COLUMN     "stageEnteredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "targetEndDate" TIMESTAMP(3);
